### ISSUE TITLE
In-depth financial statistics - Each month

### ISSUE THREAD

**Issue by Marcuzz** [everyday-as/gmodstore-issues#631]
'## Describe a feature you would like to have added to GmodStore
I would like to be able to sort out financial statistics for each month. The stats can be found here: https://www.gmodstore.com/admin/statistics

I think the new interface would fit right here: https://www.gmodstore.com/admin/financial. Also please feel free to make it even more detailed with disputes and chargebacks.

## To-do

- [x] Create a month by month and day by day overview of OUR revenue, perhaps a table and not some fancy statistics like the index page? 
- [x] Easy swapping between currency like financial VAT MOSS reports
- [x] Find out if we can make disputes more detailed, I do doubt this until the wallet service is done however

Bonus:

- [x] Split Norwegian VAT from financial VAT MOSS reports, and keep it in it's own area
